
scoreboard players set Game deeper_dark.var -12000
execute store result score @s deeper_dark.var run data get entity @s warden_spawn_tracker.ticks_since_last_warning
scoreboard players operation @s deeper_dark.var += Game deeper_dark.var
scoreboard players set Game deeper_dark.var -20
scoreboard players operation @s deeper_dark.var /= Game deeper_dark.var

execute unless score @s deeper_dark.ancient_dark_active matches 1.. unless entity @s[nbt=!{warden_spawn_tracker:{warning_level:4}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level_time","fallback":"Warning Level: %s (%2$s)","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s","color":"red"},{"score":{"name":"@s","objective":"deeper_dark.var"}}],"color":"#007A8A"}]
execute unless score @s deeper_dark.ancient_dark_active matches 1.. unless entity @s[nbt=!{warden_spawn_tracker:{warning_level:3}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level_time","fallback":"Warning Level: %s (%2$s)","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s","color":"yellow"},{"score":{"name":"@s","objective":"deeper_dark.var"}}],"color":"#007A8A"}]
execute unless score @s deeper_dark.ancient_dark_active matches 1.. unless entity @s[nbt=!{warden_spawn_tracker:{warning_level:1}},nbt=!{warden_spawn_tracker:{warning_level:2}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level_time","fallback":"Warning Level: %s (%2$s)","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s"},{"score":{"name":"@s","objective":"deeper_dark.var"}}],"color":"#007A8A"}]
execute unless score @s deeper_dark.ancient_dark_active matches 1.. if entity @s[nbt={warden_spawn_tracker:{warning_level:0}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level","fallback":"Warning Level: %s","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s"}],"color":"#007A8A"}]

execute if score @s deeper_dark.ancient_dark_active matches 1.. unless entity @s[nbt=!{warden_spawn_tracker:{warning_level:4}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level_time","fallback":"Warning Level: %s (%2$s)","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s","color":"red"},{"score":{"name":"@s","objective":"deeper_dark.var"}}],"color":"#007A8A"},{"text":" "},{"translate":"item.deeper_dark.warden_tracker.warning_ancient_dark","with":[{"score":{"objective":"deeper_dark.ancient_dark_active","name":"@s"}}],"color":"red","fallback":"The Ancient Dark Notices You! (%s)"}]
execute if score @s deeper_dark.ancient_dark_active matches 1.. unless entity @s[nbt=!{warden_spawn_tracker:{warning_level:3}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level_time","fallback":"Warning Level: %s (%2$s)","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s","color":"yellow"},{"score":{"name":"@s","objective":"deeper_dark.var"}}],"color":"#007A8A"},{"text":" "},{"translate":"item.deeper_dark.warden_tracker.warning_ancient_dark","with":[{"score":{"objective":"deeper_dark.ancient_dark_active","name":"@s"}}],"color":"red","fallback":"The Ancient Dark Notices You! (%s)"}]
execute if score @s deeper_dark.ancient_dark_active matches 1.. unless entity @s[nbt=!{warden_spawn_tracker:{warning_level:1}},nbt=!{warden_spawn_tracker:{warning_level:2}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level_time","fallback":"Warning Level: %s (%2$s)","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s"},{"score":{"name":"@s","objective":"deeper_dark.var"}}],"color":"#007A8A"},{"text":" "},{"translate":"item.deeper_dark.warden_tracker.warning_ancient_dark","with":[{"score":{"objective":"deeper_dark.ancient_dark_active","name":"@s"}}],"color":"red","fallback":"The Ancient Dark Notices You! (%s)"}]
execute if score @s deeper_dark.ancient_dark_active matches 1.. if entity @s[nbt={warden_spawn_tracker:{warning_level:0}}] run title @s actionbar [{"translate":"item.deeper_dark.warden_tracker.warning_level","fallback":"Warning Level: %s","with":[{"nbt":"warden_spawn_tracker.warning_level","entity":"@s"}],"color":"#007A8A"},{"text":" "},{"translate":"item.deeper_dark.warden_tracker.warning_ancient_dark","with":[{"score":{"objective":"deeper_dark.ancient_dark_active","name":"@s"}}],"color":"red","fallback":"The Ancient Dark Notices You! (%s)"}]