execute unless score Game deeper_dark.gamerule.sonic_boom_damage matches 10 store result storage deeper_dark:data sonic_boom_damage int 1 run scoreboard players get Game deeper_dark.gamerule.sonic_boom_damage
execute unless entity @s[tag=deeper_dark.sonic_blaster] positioned ~-.5 ~-.5 ~-.5 as @e[dx=0,dy=0,dz=0,type=!item,type=!minecraft:experience_orb] unless entity @s[advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] unless entity @s[tag=deeper_dark.sonic_blaster] unless score Game deeper_dark.gamerule.sonic_boom_damage matches 10 run function deeper_dark:armor/sonicattack_gamerule with storage deeper_dark:data
execute unless entity @s[tag=deeper_dark.sonic_blaster] positioned ~-.5 ~-.5 ~-.5 as @e[dx=0,dy=0,dz=0,type=!item,type=!minecraft:experience_orb] unless entity @s[advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] if score Game deeper_dark.gamerule.sonic_boom_damage matches 10 run damage @s 10 deeper_dark:player_sonic_boom by @n[tag=deeper_dark.selected]
execute if entity @s[tag=deeper_dark.sonic_blaster] positioned ~-.5 ~-.5 ~-.5 as @e[dx=0,dy=0,dz=0,type=!item,type=!minecraft:experience_orb] unless entity @s[advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] unless score Game deeper_dark.gamerule.sonic_boom_damage matches 10 run function deeper_dark:armor/sonicattack_blaster_gamerule with storage deeper_dark:data
execute if entity @s[tag=deeper_dark.sonic_blaster] positioned ~-.5 ~-.5 ~-.5 as @e[dx=0,dy=0,dz=0,type=!item,type=!minecraft:experience_orb] unless entity @s[advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] if score Game deeper_dark.gamerule.sonic_boom_damage matches 10 run damage @s 10 minecraft:sonic_boom by @n[tag=deeper_dark.selected]
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run particle dust{color:[0.498,0.247,0.698],scale:1} ^ ^ ^ 0.4 0.4 0.4 1 10 force
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:block.amethyst_block.resonate player @a ~ ~ ~ 2 1
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:block.amethyst_block.resonate player @a ~ ~ ~ 2 1.2
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:block.amethyst_block.resonate player @a ~ ~ ~ 2 1.4
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:block.amethyst_block.resonate player @a ~ ~ ~ 2 1.6
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:block.amethyst_block.resonate player @a ~ ~ ~ 2 1.8
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:block.amethyst_block.resonate player @a ~ ~ ~ 2 2
execute positioned ~-.5 ~-.5 ~-.5 as @a[dx=0,dy=0,dz=0,advancements={deeper_dark:functions/using_shield=true}] unless entity @s[tag=deeper_dark.selected] anchored eyes run playsound minecraft:item.shield.block player @a ~ ~ ~ 2 2
particle minecraft:sonic_boom ~ ~ ~ 0 0 0 1 1 force