#1
execute if score @s deeper_dark.sculk_converter.fragments matches 1 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"_XXXXXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 1 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥XXXXXXX"}
#2
execute if score @s deeper_dark.sculk_converter.fragments matches 2 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"__XXXXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 2 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥_XXXXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 2 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥XXXXXX"}
#3
execute if score @s deeper_dark.sculk_converter.fragments matches 3 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"___XXXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 3 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥__XXXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 3 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥_XXXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 3 if score @s deeper_dark.sculk_converter.flames matches 3 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥XXXXX"}
#4
execute if score @s deeper_dark.sculk_converter.fragments matches 4 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"____XXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 4 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥___XXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 4 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥__XXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 4 if score @s deeper_dark.sculk_converter.flames matches 3 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥_XXXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 4 if score @s deeper_dark.sculk_converter.flames matches 4 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥XXXX"}
#5
execute if score @s deeper_dark.sculk_converter.fragments matches 5 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"_____XXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 5 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥____XXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 5 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥___XXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 5 if score @s deeper_dark.sculk_converter.flames matches 3 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥__XXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 5 if score @s deeper_dark.sculk_converter.flames matches 4 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥_XXX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 5 if score @s deeper_dark.sculk_converter.flames matches 5 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥XXX"}
#6
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"______XX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥_____XX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥____XX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 3 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥___XX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 4 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥__XX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 5 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥_XX"}
execute if score @s deeper_dark.sculk_converter.fragments matches 6 if score @s deeper_dark.sculk_converter.flames matches 6 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥🔥XX"}
#7
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"_______X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥______X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥_____X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 3 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥____X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 4 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥___X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 5 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥__X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 6 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥🔥_X"}
execute if score @s deeper_dark.sculk_converter.fragments matches 7 if score @s deeper_dark.sculk_converter.flames matches 7 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥🔥🔥X"}
#8
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 0 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"________"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 1 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥_______"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 2 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥______"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 3 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥_____"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 4 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥____"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 5 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥___"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 6 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥🔥__"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 7 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥🔥🔥_"}
execute if score @s deeper_dark.sculk_converter.fragments matches 8 if score @s deeper_dark.sculk_converter.flames matches 8 run data modify entity @e[tag=deeper_dark.sculk_converter_fragments,distance=0...1,limit=1,sort=nearest] text set value {"color":"aqua","text":"🔥🔥🔥🔥🔥🔥🔥🔥"}
