tellraw @s {"translate":"deeper_dark.gui.gamerules","with":[{"translate":"deeper_dark.name","click_event":{"action":"open_url","url":"https://www.planetminecraft.com/data-pack/deeper-dark-dimension/"},"color":"#007A8A","hover_event":{"action":"show_text","value":[{"text":"Go To Website"}]},"fallback":"Deeper Dark"}],"color":"white","fallback":"%s Gamerules:"}


tellraw @s [{"translate":"deeper_dark.gui.gamerules.disable_keepinventory_override","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.disable_keepinventory_override "},"color":"green","fallback":"Disable keepInventory Override","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.disable_keepinventory_override.desc","fallback":"Disables a feature that causes players to drop their inventory while in the deeper dark, even when keepInventory is on. The dropped items are indestructable and cannot despawn.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.disable_keepinventory_override"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.disable_screen_shake","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.disable_screen_shake "},"color":"green","fallback":"Disable Screen Shake","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.disable_screen_shake.desc","fallback":"Disables screen shake for all players.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.disable_screen_shake"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.disable_sculk_conversion","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.disable_sculk_conversion "},"color":"green","fallback":"Disable Sculk Conversion","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.disable_sculk_conversion.desc","fallback":"Sculk converters cannot be created and won't convert items.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.disable_sculk_conversion"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.disable_portal_particles","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.disable_portal_particles "},"color":"green","fallback":"Disable Portal Particles","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.disable_portal_particles.desc","fallback":"Disables the particles and sounds that indicate that teleportation in/out of the deeper dark is possible.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.disable_portal_particles"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.shockwave_emits_light","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.shockwave_emits_light "},"color":"green","fallback":"Shockwave Emits Light","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.shockwave_emits_light.desc","fallback":"Allows shockwaves to emit block light.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.shockwave_emits_light"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.shockwave_can_dig","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.shockwave_can_dig "},"color":"green","fallback":"Shockwave Can Dig","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.shockwave_can_dig.desc","fallback":"Allows shockwaves to dig into the ground and despawn.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.shockwave_can_dig"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.shrieker_sense_scan_limit","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.shrieker_sense_scan_limit "},"color":"green","fallback":"Shrieker Sense Scan Limit","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.shrieker_sense_scan_limit.desc","fallback":"How far away the shrieker sense enchantment can highlight shriekers.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.range","fallback":"[Number Between %1$s and %2$s]","with":["0","1024"],"color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.shrieker_sense_scan_limit"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.disable_portals","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.disable_portals "},"color":"green","fallback":"Disable Portals","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.disable_portals.desc","fallback":"Disables the creation and usage of portals.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.boolean","fallback":"[1 Is True, 0 Is False]","color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.disable_portals"}}]

tellraw @s [{"translate":"deeper_dark.gui.gamerules.sonic_boom_damage","click_event":{"action":"suggest_command","command":"/scoreboard players set Game deeper_dark.gamerule.sonic_boom_damage "},"color":"green","fallback":"Sonic Boom Damage","hover_event":{"action":"show_text","value":[{"translate":"deeper_dark.gui.gamerules.hint","fallback":"Click to Change","color":"yellow"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.sonic_boom_damage.desc","fallback":"Controls how much damage deeper dark's sonic attacks do.","color":"white"},{"text":"\n"},{"translate":"deeper_dark.gui.gamerules.input_type.range","fallback":"[Number Between %1$s and %2$s]","with":["0","2147483647"],"color":"light_purple"}]}},{"color":"white","text":" = "},{"color":"aqua","score":{"name":"Game","objective":"deeper_dark.gamerule.sonic_boom_damage"}}]


tellraw @s ["\n",{"translate":"deeper_dark.gui.gamerules.hint","color":"yellow","fallback":"Click to Change"}]