#{width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15}}

#up
summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n        ■       \n    ■ ■ ■ ■     \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n      ■         \n    ■ ■ ■ ■     \n      ■         \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n    ■ ■ ■ ■     \n        ■       \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n    ■ ■ ■ ■     \n      ■         \n      ■         \n                \n                "}]}


#north
summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n        ■       \n    ■ ■ ■ ■     \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n      ■         \n    ■ ■ ■ ■     \n      ■         \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n    ■ ■ ■ ■     \n        ■       \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n    ■ ■ ■ ■     \n      ■         \n      ■         \n                \n                "}]}


#east
summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n        ■       \n    ■ ■ ■ ■     \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n      ■         \n    ■ ■ ■ ■     \n      ■         \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n    ■ ■ ■ ■     \n        ■       \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n    ■ ■ ■ ■     \n      ■         \n      ■         \n                \n                "}]}


#south
summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n        ■       \n    ■ ■ ■ ■     \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n      ■         \n    ■ ■ ■ ■     \n      ■         \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n    ■ ■ ■ ■     \n        ■       \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n    ■ ■ ■ ■     \n      ■         \n      ■         \n                \n                "}]}


#west
summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n        ■       \n    ■ ■ ■ ■     \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n      ■         \n    ■ ■ ■ ■     \n      ■         \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n    ■ ■ ■ ■     \n        ■       \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n    ■ ■ ■ ■     \n      ■         \n      ■         \n                \n                "}]}


#down
summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n        ■       \n    ■ ■ ■ ■     \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n      ■         \n    ■ ■ ■ ■     \n      ■         \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n        ■       \n    ■ ■ ■ ■     \n        ■       \n        ■       \n                \n                "}]}

summon text_display ~ ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.boss.block.off"],brightness:{sky:15,block:15},background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,0.5f],scale:[0.5f,0.5f,0f]},text:[{"color":"#000000","text":"                \n                \n      ■         \n    ■ ■ ■ ■     \n      ■         \n      ■         \n                \n                "}]}


#Generated with EMD's datapack texture generator 2