#width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"]

#up
summon text_display ~ ~0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#1b7b6b","text":"■ "},{"color":"#209581","text":"■         "},{"color":"#2ccdb1","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n                \n                \n                \n                \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n"},{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ "}]}

summon text_display ~ ~0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#2ccdb1","text":"■         "},{"text":"■ "},{"color":"#1b7b6b","text":"■ \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ \n                \n                \n                \n                \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n"},{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n                \n                \n                \n                \n"},{"text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n"},{"color":"#1b7b6b","text":"■ "},{"text":"■         "},{"color":"#2ccdb1","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,-90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n                \n                \n                \n                \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#2ccdb1","text":"■         "},{"color":"#209581","text":"■ "},{"color":"#1b7b6b","text":"■ "}]}


#north
summon text_display ~ ~ ~-0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#1b7b6b","text":"■ "},{"color":"#209581","text":"■         "},{"color":"#2ccdb1","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n                \n                \n                \n                \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n"},{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ "}]}

summon text_display ~ ~ ~-0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#2ccdb1","text":"■         "},{"text":"■ "},{"color":"#1b7b6b","text":"■ \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ \n                \n                \n                \n                \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n"},{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~ ~-0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n                \n                \n                \n                \n"},{"text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n"},{"color":"#1b7b6b","text":"■ "},{"text":"■         "},{"color":"#2ccdb1","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~ ~-0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[180F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n                \n                \n                \n                \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#2ccdb1","text":"■         "},{"color":"#209581","text":"■ "},{"color":"#1b7b6b","text":"■ "}]}


#east
summon text_display ~0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#1b7b6b","text":"■ "},{"color":"#209581","text":"■         "},{"color":"#2ccdb1","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n                \n                \n                \n                \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n"},{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ "}]}

summon text_display ~0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#2ccdb1","text":"■         "},{"text":"■ "},{"color":"#1b7b6b","text":"■ \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ \n                \n                \n                \n                \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n"},{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ "}]}

summon text_display ~0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n                \n                \n                \n                \n"},{"text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n"},{"color":"#1b7b6b","text":"■ "},{"text":"■         "},{"color":"#2ccdb1","text":"■ "},{"text":"■ "}]}

summon text_display ~0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[-90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n                \n                \n                \n                \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#2ccdb1","text":"■         "},{"color":"#209581","text":"■ "},{"color":"#1b7b6b","text":"■ "}]}


#south
summon text_display ~ ~ ~0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#1b7b6b","text":"■ "},{"color":"#209581","text":"■         "},{"color":"#2ccdb1","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n                \n                \n                \n                \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n"},{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ "}]}

summon text_display ~ ~ ~0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#2ccdb1","text":"■         "},{"text":"■ "},{"color":"#1b7b6b","text":"■ \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ \n                \n                \n                \n                \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n"},{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~ ~0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n                \n                \n                \n                \n"},{"text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n"},{"color":"#1b7b6b","text":"■ "},{"text":"■         "},{"color":"#2ccdb1","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~ ~0.51 {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n                \n                \n                \n                \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#2ccdb1","text":"■         "},{"color":"#209581","text":"■ "},{"color":"#1b7b6b","text":"■ "}]}


#west
summon text_display ~-0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#1b7b6b","text":"■ "},{"color":"#209581","text":"■         "},{"color":"#2ccdb1","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n                \n                \n                \n                \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n"},{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ "}]}

summon text_display ~-0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#2ccdb1","text":"■         "},{"text":"■ "},{"color":"#1b7b6b","text":"■ \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ \n                \n                \n                \n                \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n"},{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ "}]}

summon text_display ~-0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n                \n                \n                \n                \n"},{"text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n"},{"color":"#1b7b6b","text":"■ "},{"text":"■         "},{"color":"#2ccdb1","text":"■ "},{"text":"■ "}]}

summon text_display ~-0.51 ~ ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[90F,0F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n                \n                \n                \n                \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#2ccdb1","text":"■         "},{"color":"#209581","text":"■ "},{"color":"#1b7b6b","text":"■ "}]}


#down
summon text_display ~ ~-0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#1b7b6b","text":"■ "},{"color":"#209581","text":"■         "},{"color":"#2ccdb1","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n                \n                \n                \n                \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n"},{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ "}]}

summon text_display ~ ~-0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.4751f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#2ccdb1","text":"■         "},{"text":"■ "},{"color":"#1b7b6b","text":"■ \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ \n                \n                \n                \n                \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n"},{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~-0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[-0.0125f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#209581","text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#ffffff","text":"■ \n"},{"color":"#2ccdb1","text":"■ "},{"color":"#4aedd1","text":"■           ■ \n                \n                \n                \n                \n"},{"text":"■ "},{"color":"#a2f6e7","text":"■         "},{"color":"#4aedd1","text":"■ "},{"color":"#a2f6e7","text":"■ \n"},{"color":"#1b7b6b","text":"■ "},{"text":"■         "},{"color":"#2ccdb1","text":"■ "},{"text":"■ "}]}

summon text_display ~ ~-0.51 ~ {width:1f,height:1f,teleport_duration:2,Tags:["deeper_dark.anticatalyst.texture"],background:0,line_width:800,alignment:"left",Rotation:[0F,90F],width:1f,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0.05f,-0.5376000000000001f,-0.01f],scale:[0.5f,0.5f,0f]},text:[{"color":"#ffffff","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n"},{"color":"#4aedd1","text":"■           ■ "},{"color":"#2ccdb1","text":"■ \n                \n                \n                \n                \n"},{"color":"#a2f6e7","text":"■ "},{"color":"#4aedd1","text":"■         "},{"color":"#a2f6e7","text":"■ "},{"color":"#209581","text":"■ \n■ "},{"color":"#2ccdb1","text":"■         "},{"color":"#209581","text":"■ "},{"color":"#1b7b6b","text":"■ "}]}


#Generated with EMD's datapack texture generator 2